name: notebooks
dependencies:
  # Packages used to start the jupyter server
  - python=3.5.3  # not using 3.6 because some dependencies still need 3.5
  - ipython-notebook=4.0.4
  - nb_conda=2.0.0

  # Packages used by the kernel where notebooks are run
  # (They could be added to a separate env, but are kept together here for convenience)
  - python=3.5.3
  - ipykernel=4.6.1
  - ipywidgets=6.0.0
  - numpy=1.12.1
  - scipy=0.19.0
  - seaborn=0.7.1
  - sympy=1.0
